title: Chrysopoeia
root: /
baseurl: /
url: http://chrysopoeia-site.github.io
collections:
  blog:
    output: true
    permalink: /:categories/:month/:day/:title/
  writing:
    output: true
    permalink: /:categories/:title/
